### ISSUE TITLE
Update Readme file - Dropbox no longer allows

### ISSUE THREAD

**Issue by marigerr** [Esri/basic-map-storytelling-template-js#7]
Current README file lines 61-63>

> **How to deploy the application on a web server?**
> If you are not familiar with web servers here is three solutions:
> Use a free hosting service like Dropbox, you may have to [configure Dropbox to enable webpage hosting](https://www.dropbox.com/enable_public_folder)

However as of October 3, 2016, free dropbox users can no longer use shared links to render HTML.   Paid users will no longer be able to use this feature after September 1, 2017.
https://www.dropbox.com/help/16

The link in the ReadMe file on line 63 is no longer active and needs to be removed/updated.

**Comment by ssylvia** [comment]
Thanks for letting us know. I've updated the readme to point to another free hosting service.
